[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

  [[redirects]]
  from = "/app/trip-direction/store/trip-direction.effects.ts"
  to = "/assets/locations.json"
  status = 200
